name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Rodar o workflow quando houver push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código no repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # Logar no Docker Hub usando o Personal Access Token
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # Build da imagem Docker
    - name: Build Docker image
      run: docker build -t hersonpc/hdt-dashboard:latest .

    # Fazer push da imagem Docker para o Docker Hub
    - name: Push Docker image
      run: docker push hersonpc/hdt-dashboard:latest